spring:
  application:
    name: data-store
  kafka:
    bootstrap-servers:
      - kafka:9092
    consumer:
      group-id:  forex-data-storer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted: org.home.forex.model
        spring.json.trusted.packages: org.home.forex.model
  datasource:
    url: jdbc:mysql://mysql:3306/forex
    username: forex
    password: demo
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    show-sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9090/eureka
  instance:
      statusPageUrl: http://localhost:84/actuator/info
      healthCheckUrlPath: http://localhost:84/actuator/health

store:
  topic:
    input: aggregated-quotes