  version: "3"

  services:
    feed:
      image: openjdk:8-jre-alpine
      restart: unless-stopped
      command: java ${java_opts} -jar /app/data-provider-${version}.jar
      volumes:
        - ./services/data-provider/target:/app
      environment:
        - EUREKA_CLIENT_ENABLED=${enable_discovery_client}
      ports:
        - "81:8080"
        - "5005:5005"

    adapter:
      depends_on:
        - kafka
      image: openjdk:8-jre-alpine
      restart: unless-stopped
      command: java ${java_opts} -jar /app/data-adapter-${version}.jar
      volumes:
        - ./services/data-adapter/target:/app
      environment:
        - FEED_URL=${feedUrl}
        - EUREKA_CLIENT_ENABLED=${enable_discovery_client}
      ports:
        - "82:8080"
        - "5006:5005"

    aggregator:
      depends_on:
        - kafka
      image: fabric8/java-centos-openjdk8-jdk
      restart: unless-stopped
      command: java ${java_opts} -jar /app/data-aggregator-${version}.jar
      volumes:
        - ./services/data-aggregator/target:/app
      environment:
        - EUREKA_CLIENT_ENABLED=${enable_discovery_client}
      ports:
        - "83:8080"
        - "5007:5005"

    store:
      depends_on:
        - kafka
        - mysql
      image: openjdk:8-jre-alpine
      restart: unless-stopped
      command: java ${java_opts} -jar /app/data-store-${version}.jar
      volumes:
        - ./services/data-store/target:/app
      environment:
        - EUREKA_CLIENT_ENABLED=${enable_discovery_client}
      ports:
        - "84:8080"
        - "5008:5005"

    eureka:
      image: openjdk:8-jre-alpine
      restart: unless-stopped
      command: java -jar /app/eureka-${version}.jar
      volumes:
        - ./services/eureka/target:/app
      ports:
        - "9090:9090"

    zookeeper:
      image: bitnami/zookeeper:latest
      restart: unless-stopped
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
      depends_on:
        - zookeeper
      image: bitnami/kafka:latest
      restart: unless-stopped
      ports:
        - "9092:9092"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    mysql:
      depends_on:
        - kafka
      image: mysql
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=demo
        - MYSQL_DATABASE=forex
        - MYSQL_USER=forex
        - MYSQL_PASSWORD=demo

    apache:
      image: 'bitnami/apache:latest'
      restart: unless-stopped
      volumes:
        - ./http/docs:/app
        - ./http/vhost.conf:/vhosts/my_vhost.conf:ro
      ports:
        - '80:8080'
