spring:
  application:
    name: data-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9090/eureka
  instance:
    statusPageUrl: http://localhost:81/actuator/info
    healthCheckUrlPath: http://localhost:81/actuator/health

feed:
  symbol: EURUSD
  basePrice: 1.10